name: Publish Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # github.sha, github.ref : https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release
    #
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: pocket-apps/action-update-version@v1
      with:
        files: 'harmony/__init__.py'
        version-regexp: '\d+.\d+.\d+'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - shell: bash
      env:
        REPO_PASS: ${{ secrets.PYPI }}
      run: |
        VERSION=$(echo ${{github.event.release.tag_name}} | cut -c2-) make build
        make publish
