name: Publish Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - shell: bash
      env:
        REPO_PASS: ${{ secrets.PYPI }}
        VERSION_TAG: ${{github.event.release.tag_name}}
      run: |
        VERSION=$(echo "${VERSION_TAG}" | cut -c2-) make build
        echo "make publish"
        # make publish

        git config --global user.name $(git show -s --format='%an')
        git config --global user.email $(git show -s --format='%ae')
        git commit -a -m "Update release version (Automated commit)"
        git add .
        git commit -m "Version bump to ${VERSION_TAG}"
        git tag -f "${VERSION_TAG}"
        git push
        git push origin "${VERSION_TAG}"
